security:
    encoders:
        App\Entity\Gestionnaire:
            algorithm: bcrypt    

    providers:
        in_database:
            entity:
                class: App\Entity\Gestionnaire
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: in_database

            form_login:
                login_path: connexion
                check_path: connexion
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: deconnexion
                target: connexion

    access_control:
        - { path: ^/(connexion|inscription), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: [ROLE_USER, ROLE_ADMIN] }
